# Import Libraries 

In [5]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

# Import Data


In [ ]:
# Load the iris dataset from sklearn
iris = load_iris()

# dataset = read_csv('iris.csv')  # if a CSV file is available

# Create a DataFrame from the iris dataset
dataset = pd.DataFrame(data=iris.data, columns=iris.feature_names)
dataset['target'] = iris.target

# Display the first few rows of the dataset
dataset.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [ ]:
# Display the dataset description
dataset.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [12]:
# Separate features and target variable
X = dataset.iloc[:, :-1].values  # Features
y = dataset.iloc[:, -1].values    # Target variable 

print("Features (X):")
print(X[:5])  # Display first 5 rows of features
print("\nTarget (y):")
print(y[:5])  # Display first 5 target values

Features (X):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Target (y):
[0 0 0 0 0]


# Missing Data

In [13]:
# Check for missing data in each column
missing_data = dataset.isnull().sum()
print("Missing data in each column:")
print(missing_data)

Missing data in each column:
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64


In [14]:
from sklearn.impute import SimpleImputer

# Configure the SimpleImputer to replace missing values with the mean of each column
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

imputer.fit(X[:, 1:3])  # Fit the imputer on the second and third columns (index 1 and 2)
imputer.transform(X[:, 1:3])  # Transform the data to fill missing values

X[:, 1:3] = imputer.transform(X[:, 1:3])  # Update the original data with the transformed values

# Display the dataset after handling missing values
print("Dataset after handling missing values:")
print(dataset.head())

Dataset after handling missing values:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
